# Generated by Django 5.0.3 on 2026-07-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_streak",
            field=models.IntegerField(
                default=0, help_text="Consecutive days practiced."
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_practice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="xp_points",
            field=models.IntegerField(
                default=0, help_text="Experience points earned through practice."
            ),
        ),
    ]
