# Generated by Django 5.0.3 on 2026-07-27 14:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpeechAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(upload_to="audio_recordings/%Y/%m/%d/"),
                ),
                (
                    "transcribed_text",
                    models.TextField(
                        blank=True, help_text="Whisper output.", null=True
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        default=0.0, help_text="Calculated accuracy (0-100%)."
                    ),
                ),
                ("phoneme_scores", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TherapyExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "target_text",
                    models.TextField(
                        help_text="The exact sentence/phrase the user must speak."
                    ),
                ),
                (
                    "target_phonemes",
                    models.JSONField(
                        default=list, help_text="Phonemes tested in this exercise."
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Beginner"),
                            ("MEDIUM", "Intermediate"),
                            ("HARD", "Advanced"),
                        ],
                        default="EASY",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
