# Generated by Django 5.0.3 on 2026-08-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speechattempt",
            name="ai_feedback",
            field=models.TextField(
                blank=True,
                help_text="Actionable LLM-generated feedback based on the acoustic analysis.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="therapyexercise",
            name="is_interview_mode",
            field=models.BooleanField(
                default=False,
                help_text="If True, this is a professional interview question rather than a clinical phoneme test.",
            ),
        ),
    ]
